version: '3.8'

services:
  currency-api:
    build: .
    container_name: currency-conversion-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      # JWT Configuration
      - Jwt__SecretKey=docker-dev-secret-key-for-jwt-signing-change-in-production-environment
      - Jwt__Issuer=CurrencyConversionApi-Docker
      - Jwt__Audience=CurrencyConversionApi-Docker
      - Jwt__ExpirationMinutes=60
      # Exchange Rate Configuration
      - ExchangeRates__ActiveProvider=Frankfurter
      - ExchangeRates__RequestTimeout=00:00:15
      - ExchangeRates__MaxRetryAttempts=3
      # Cache Configuration
      - SmartCache__BusinessHoursTTL=00:15:00
      - SmartCache__OffHoursTTL=01:00:00
      - SmartCache__BusinessHoursStart=8
      - SmartCache__BusinessHoursEnd=20
      # Logging
      - Serilog__MinimumLevel__Default=Information
      - Serilog__MinimumLevel__Override__Microsoft=Warning
      - Serilog__MinimumLevel__Override__System=Warning
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - currency-network

networks:
  currency-network:
    driver: bridge
